CRUD, where, orderBy
nikserg/laravel-api-model pull request #2
Opened 2022-08-23 13:23 UTC by zadrogg

2022-08-23 13:42 UTC, nikserg requested changes

2022-08-23 13:42 UTC, nikserg commented on ApiModel.php
> +    public function getDateFormat()
Ненужная функция?

2022-08-23 13:42 UTC, nikserg commented on ApiModel.php
> +            $response = $connection->getClient()->request('PUT', $this->getTable() . '/' . $this->getAttributes()[0], [
1. Нужны комментарии, хотя бы на уровне функции. Это касается и других мест, все помечать не буду. Комментарии обязательны для класса и функции, более подробное комментирование приветствуется, но не обязательно.
2. `$this->getAttributes()[0]` я прямо вижу ошибку index 0 is undefined. Если там не может быть undefined, нужно описать почему

2022-08-23 13:42 UTC, nikserg commented on ApiModel.php
> +            throw new InvalidArgumentException($response['data']);
Зачем \Exception оборачивается в другой эксепшн? Это встречается и в других местах.

2022-08-23 13:42 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +
Довольно странное форматирование кода, много пустых строк. Не сказать, что это критично, но выглядит довольно странно. В phpstorm есть комбинация ctrl+alt+l, которая автоматически форматирует код. В своей ide наверняка можешь найти подобное.

2022-08-23 13:42 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +    public function getListOfModels(array $response)
Можно сделать `public function getListOfModels(array $response): ListOfModels`. Если версия языка позволяет, стоит всегда использовать типизацию.

2022-08-23 13:42 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +    public function getOrderBy(object $order)
Может сделать `public function getOrderBy(array $order)`? Тогда и конвертация не нужна будет.

2022-08-23 13:42 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +            'page'      => $order->page+1
С той стороны ожидается page на единичку больше? Как-то странно

2022-08-23 13:42 UTC, nikserg commented on ApiModelEloquentBuilder.php
> +        if ((int) $response['code'] < 200 || (int) $response['code'] > 204) {
1. У psr-запросов вроде есть что-то типа `isSuccessful()`, чтобы не проверять коды напрямую
2. И вообще лучше делать guzzle клиента, который кидает исключения в случае плохих кодов. Тогда явно проверять код ответа не нужно никогда.

2022-08-23 13:51 UTC, zadrogg commented on ApiModel.php
> +    public function getDateFormat()
backpack когда запрашивал список, он не умел работать с датой, необходимо было прокинуть в конструктор Grammar и Processor чтобы преобразовывал, я просто переопределял функцию форматирования которая ничего не делает, чтобы не терять время

2022-08-23 14:04 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +
я когда пишу код сам их проставляю для читабельности, форматер кода в IDE стоит

2022-08-23 14:05 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +    public function getOrderBy(object $order)
согласен, просто работать с объектами проще, исправлю

2022-08-23 14:07 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +            'page'      => $order->page+1
перед запросом вычисляется текущая страница , если это первая страница выдает 0
### $page = $this->offset / $this->limit;
поэтому при запросе добавляем 1

2022-08-23 15:10 UTC, nikserg requested changes

2022-08-23 15:10 UTC, nikserg commented on ApiModel.php
> +     * поэтому $this->getAttributes[0] - не может быть без id
А не логичнее будет использовать $this->getId()? Или getIdentifier, не помню

2022-08-23 15:10 UTC, nikserg commented on ApiModel.php
> +     * Валидация стоит на всякий случай
Подобный подход затрудняет чтение кода. Не стоит подстраховываться от ситуаций, которые возможно когда-нибудь произойдут и ставить на них проверки. Если ситуация произойдет - проверку поставим, а пока она не нужна.
Кстати, 100% code coverage помогает избежать таких избыточных проверок: если не можешь написать адекватный тест, который покрывает выкидывание какого-то исключения, значит, оно там лишнее.
Здесь тестов нет, но можно мыслить аналогично.

2022-08-23 15:10 UTC, nikserg commented on ApiModel.php
> +     * findOrFail вызывается перед delete, мы метод переопределили и закинули в модель id
По стандарту phpdoc, первая строчка комментария - краткое описание функции, потом пустая строка, и потом подробное описание. Т.е. в этом случае можно сделать такой комментарий 

```
Удаление записи

findOrFail вызывается перед delete, мы метод переопределили и закинули в модель id...
```

2022-08-23 15:10 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +
Насколько я помню, psr строго не регламентирует пустые строки, но на других проектах у нас такого нет. Поэтому для сохранения единообразия не стоит ставить пустые строки после фигурных скобок в таких конструкциях.

2022-08-23 15:10 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +    public function getOrderBy(array $order)
Все еще функция без комментария. Возьми за правило всегда писать docblock для функций и классов.

2022-08-23 15:12 UTC, zadrogg commented on ApiModel.php
> +            $response = $connection->getClient()->request('PUT', $this->getTable() . '/' . $this->getAttributes()[0], [
исправлено

2022-08-23 15:12 UTC, zadrogg commented on ApiModel.php
> +            throw new InvalidArgumentException($response['data']);
+

2022-08-23 15:18 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +
принято, постараюсь

2022-08-23 15:18 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +    public function getListOfModels(array $response)
+

2022-08-23 15:19 UTC, zadrogg commented on ApiModelEloquentBuilder.php
> +        if ((int) $response['code'] < 200 || (int) $response['code'] > 204) {
исправлено

2022-08-23 15:27 UTC, zadrogg commented on ApiModel.php
> +     * поэтому $this->getAttributes[0] - не может быть без id
![Снимок экрана 2022-08-23 в 18 26 05](https://user-images.githubusercontent.com/62801553/186198651-576ea5db-470e-48a5-9851-798ff746ab47.png)
мы добавили primary в атрибуты, при получении getKey  null, мы же не сохранили еще модель

2022-08-23 15:28 UTC, zadrogg commented on ApiModel.php
> +     * Валидация стоит на всякий случай
принято

2022-08-23 15:29 UTC, zadrogg commented on ApiModel.php
> +     * findOrFail вызывается перед delete, мы метод переопределили и закинули в модель id
принято, исправил, не работал с phpdoc, учту

2022-08-23 15:34 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +    public function getOrderBy(array $order)
принято

2022-08-24 04:37 UTC, nikserg requested changes

2022-08-24 04:37 UTC, nikserg commented on ApiModel.php
> +     * поэтому $this->getAttributes[0] - не может быть без id
Тогда для повышения читабельности предлагаю выделить `$this->getAttributes()[0]` в отдельную функцию, назвать ее как-то типа `getIdBeforeSave()`, в комментарии к ней описать ситуацию и использовать везде её.

2022-08-24 04:37 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        } catch (InvalidArgumentException $e) {
Бессмысленный try-catch

2022-08-24 04:37 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +
Многовато пустых строк

2022-08-24 04:37 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +
Многовато пустых строк

2022-08-24 05:25 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        } catch (InvalidArgumentException $e) {
почему ? если пришла ошибка с сертификатов guzzle выкидывает exception, мы делаем исключение чтобы отобразить, можно было и через if сделать, но подумал что лучше обычным исключением

2022-08-24 05:26 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        } catch (InvalidArgumentException $e) {
почему ? если пришла ошибка с сертификатов guzzle выкидывает exception, мы делаем исключение чтобы отобразить, можно было и через if сделать, но подумал что лучше обычным исключением

2022-08-24 05:27 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +
исправил

2022-08-24 05:28 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +
исправил

2022-08-24 05:32 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        } catch (InvalidArgumentException $e) {
Ты ловишь InvalidArgumentException и выкидываешь InvalidArgumentException. Убери try-catch и ничего не изменится

2022-08-24 05:33 UTC, nikserg requested changes
Один из комментариев не обработан + новый комментарий в дискуссии

2022-08-24 05:34 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        } catch (InvalidArgumentException $e) {
убрал

2022-08-24 05:38 UTC, nikserg approved these changes

2022-08-24 05:38 UTC, merged