Crud
nikserg/laravel-api-model pull request #3
Opened 2022-08-26 13:54 UTC by zadrogg

2022-08-26 14:01 UTC, nikserg requested changes

2022-08-26 14:01 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        if (!array_key_exists('data', $decoded))
Фигурные скобки должны быть всегда. Используй форматирование кода по стандарту psr

2022-08-26 14:01 UTC, nikserg commented on ApiModel.php
> +    public function hierarchy(): Collection
Этой функции не место тут. Она специфична для конкретной модели. Ее нужно делать в модели на уровне приложения.

2022-08-26 14:01 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +            throw new InvalidArgumentException('Missing a key data');
Можно добавить больше информации в ошибку - передать $body

2022-08-29 09:44 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +            throw new InvalidArgumentException('Missing a key data');
исправлено

2022-08-29 09:44 UTC, zadrogg commented on ApiModel.php
> +    public function hierarchy(): Collection
убраи

2022-08-29 09:45 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        if (!array_key_exists('data', $decoded))
исправил

2022-08-29 09:47 UTC, nikserg approved these changes

2022-08-29 09:49 UTC, merged