[crud][task] custom_url model
nikserg/laravel-api-model pull request #5
Opened 2022-08-29 12:52 UTC by zadrogg

2022-08-29 13:24 UTC, nikserg requested changes

2022-08-29 13:24 UTC, nikserg commented on ApiModel.php
> +    public function newEloquentBuilder($query)
С чем связано удаление возвращаемого типа? Это встречается много где, все места указывать не буду.

2022-08-29 13:24 UTC, nikserg commented on ApiModel.php
> +        $url = $this->custom_url ?? $this->getTable();
Лучше сделать `protected function getUpdateUrl() { return $this->getTable(); }`, чтобы в наследнике можно было переопределить эту функцию при необходимости.

2022-08-29 13:24 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        $url = $this->custom_url ?? $this->from;
Аналогично `getUpdateUrl`, здесь можно сделать `getViewUrl`.

2022-08-29 13:24 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +    public function __construct(ConnectionInterface $connection, ?string $custom_url = null)
camelCase

2022-08-29 13:28 UTC, zadrogg commented on ApiModel.php
> +    public function newEloquentBuilder($query)
думаю случайно затер когда работал из вендора

2022-08-29 13:28 UTC, zadrogg commented on ApiModel.php
> +    public function newEloquentBuilder($query)
исправил

2022-08-29 13:29 UTC, zadrogg commented on ApiModel.php
> +        $url = $this->custom_url ?? $this->getTable();
Исправил

2022-08-29 13:30 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        $url = $this->custom_url ?? $this->from;
Исправил

2022-08-29 13:34 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +    public function __construct(ConnectionInterface $connection, ?string $custom_url = null)
Исправил

2022-08-29 13:39 UTC, nikserg requested changes

2022-08-29 13:39 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        $url = $this->customUrl ?? $this->getCreateOrViewUrl();
Если есть `getCreateOrViewUrl`, тогда `$this->customUrl` не нужен. Вместо того, чтобы переопределять в наследнике `customUrl`, можно сразу переопределить `getCreateOrViewUrl`. И тогда тут будет просто `$url = $this->getCreateOrViewUrl();`.

2022-08-29 13:39 UTC, nikserg commented on ApiModel.php
> +    public function qualifyColumn($column)
Удаление возвращаемого типа

2022-08-29 13:39 UTC, nikserg commented on ApiModel.php
> +            $this->custom_url
camelCase

2022-08-29 13:42 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        $url = $this->customUrl ?? $this->getCreateOrViewUrl();
Согласен, не подумал

2022-08-29 13:42 UTC, zadrogg commented on ApiModel.php
> +    public function qualifyColumn($column)
Исправил

2022-08-29 13:43 UTC, zadrogg commented on ApiModel.php
> +            $this->custom_url
исправил

2022-08-29 14:01 UTC, nikserg requested changes

2022-08-29 14:01 UTC, nikserg commented on ApiModel.php
> +            $response = $this->getConnection()->getClient()->request('PUT', $this->getUpdateUrl(); . '/' . $this->getIdBeforeSave(), [
`;` посреди строки?

2022-08-29 14:01 UTC, nikserg commented on ApiModel.php
> +        return $this->customUrl ?? $this->getTable();
`customUrl` вообще не нужен.

Если пользователь захочет тут ксатомный урл, он просто переопределит весь метод getUpdateUrl.

2022-08-29 14:01 UTC, nikserg commented on ApiModelBaseQueryBuilder.php
> +        return $this->customUrl ?? $this->from;
Аналогичные замечания

2022-08-29 14:06 UTC, zadrogg commented on ApiModel.php
> +            $response = $this->getConnection()->getClient()->request('PUT', $this->getUpdateUrl(); . '/' . $this->getIdBeforeSave(), [
исправил

2022-08-29 14:07 UTC, zadrogg commented on ApiModel.php
> +        return $this->customUrl ?? $this->getTable();
понял, исправил

2022-08-29 14:07 UTC, zadrogg commented on ApiModelBaseQueryBuilder.php
> +        return $this->customUrl ?? $this->from;
понял, исправил

2022-08-30 05:35 UTC, nikserg requested changes

2022-08-30 05:35 UTC, nikserg commented on ApiModel.php
> +    protected function getCustomUrl(): string
Почему-то используется только в методе update. В delete, например, по-прежнему используется getTable. Т.е. это либо getCustomUrlForUpdate, либо нужно, чтобы эта функция использовалась во всех методах.

2022-08-30 06:27 UTC, zadrogg commented on ApiModel.php
> +    protected function getCustomUrl(): string
исправил

2022-08-30 06:30 UTC, nikserg approved these changes

2022-08-30 06:31 UTC, merged